name: Run test commands

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-check:
    uses: fizyk/actions-reuse/.github/workflows/shared-pr-check.yml@v3.1.1

  resizer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install package
        run: pip install .
      - name: Run resizer --help
        run: resizer --help
