name: Run test commands

on:
  pull_request:
    branches: [ main ]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: fizyk/actions-reuse/.github/actions/pipenv@v2.4.0
        with:
          python-version: "3.11"
          command: tbump --dry-run --only-patch $(pipenv run tbump current-version)"-x"
  towncrier:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: fizyk/actions-reuse/.github/actions/pipenv@v2.4.0
        with:
          python-version: "3.11"
          command: towncrier check --compare-with origin/main
          fetch-depth: 0

  resizer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install package
        run: pip install .
      - name: Run resizer --help
        run: resizer --help
