name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@v3.1.1
    with:
      python-versions: '["3.12"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
